""" Project Euler - Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""
fib_list = [0,1]

def fib_builder(lim):
    while fib_list[-1] < lim:
       temp = fib_list[len(fib_list) - 2] + fib_list[len(fib_list) - 1]
       fib_list.append(temp)
    return even_fib_sum(fib_list)

def even_fib_sum(list):
    sum = 0
    for x in list:
        if x % 2 == 0:
            sum += x
    return sum

print(fib_builder(4000000))
print(fib_list)